### ISSUE TITLE
Please register a new (patch) version with identical content

### ISSUE THREAD

**Issue by dhanak** [kul-optec/AbstractOperators.jl#19]
The HEAD is still compatible with the newest versions of the DSP and FFTW libraries, and even the `[compat]` section of the `Project.toml` file permits them. However, the general registry recorded a narrower compatibility range, limiting DSP to version 0.6.

Bumping the patch version to 0.2.3 and reregistering the package would solve this issue.

Thanks!

**Comment by lostella** [comment]
@dhanak I went for a more radical change, see #20. What do you think? Fingers crossed tests are still green after all this time.

**Comment by dhanak** [comment]
Okay, let's try that!

**Comment by dhanak** [comment]
That was quick, thanks a lot!
